stages:
  data_ingestion:
    cmd: python3 src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python3 src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema.yaml
      - artifacts/data_ingestion
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python3 src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_validation/status.txt
    outs:
      - artifacts/data_transformation

  model_trainer:
    cmd: python3 src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlProject/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python3 src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_transformation/test.csv
      - artifacts/model_trainer/model.joblib

    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false
